### ISSUE TITLE
Lesson 4 import wind direction as wind vane

### ISSUE THREAD

**Issue by Sivashankaruav** [raspberrypilearning/sensing-the-weather#12]
import wind_direction as wind_vane
ImportError: NoModule named Wind_direction

**Comment by lawsie** [comment]
Hello, have you installed the software from the Weather Station guide? https://www.raspberrypi.org/learning/weather-station-guide/ 

The wind_direction library is part of the weather station software which you need to have installed on your Pi for this code to work.

Also make sure that wind_direction has no capitals.
