### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by LornaLynch** [raspberrypilearning/sensing-the-weather#9]
I just noticed that there are two images missing in master/guides/GPIO/pull_up_down.md, which is linked in this resource (pull up wire and pull down wire). Can we fix this, or do I need to go via the guide?

**Comment by MissPhilbin** [comment]
Hi Lorna, thanks for looking at this. I've asked a member of the team to review the whole resource and fix any problems on a branch, which we will then submit for copy edits before a merge. This resource has a complicated history and should never have gone live without completion and a copy edit which the owner of the project knew at the time.

**Comment by LornaLynch** [comment]
Thank you!
